In [1]:
import numpy as np

In [3]:
a = np.array([[1,2,3], [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [5]:
b = np.array([12, 13])
print(b)

[12 13]


In [9]:
a[:, 0] += b

In [14]:
a * a

array([[13,  2,  3],
       [17,  5,  6]])