In [2]:
import numpy as np

In [59]:
a = np.array([[1,2,3], [5,6,7]])
print(a)

[[1 2 3]
 [5 6 7]]


In [77]:
b = np.array([2,3, 3])
print(b)

[2 3 3]


In [66]:
c = b.reshape(3, 1)

In [67]:
a + c.T

array([[ 3,  5,  6],
       [ 7,  9, 10]])

In [87]:
np.concatenate((b[:1], b[5:]))

array([2])

In [80]:
b[2:]

array([3])