In [1]:
import numpy as np
from itertools import product

In [3]:
a = np.array([[1,2,3], [2,3,4],[5,6,7]])
print(a)

[[1 2 3]
 [2 3 4]
 [5 6 7]]


In [44]:
def softmax(scores):
    if len(scores.shape) == 1:
        scores = scores.reshape(1, scores.shape[0])
    scores = scores - scores.max(axis=1).reshape(scores.shape[0], 1)
    scores = np.exp(scores)
    print(scores.shape)
    sum = scores.sum(axis=1)
    print(sum.shape)
    print(scores.shape)
    sum = sum.reshape(scores.shape[0], 1)
    scores = scores / sum
    return scores

In [45]:
softmax(a[0])

(1, 3)
(1,)
(1, 3)


array([[0.09003057, 0.24472847, 0.66524096]])

In [55]:
scores = a[0]
scores = scores.reshape(1, scores.shape[0])
scores = scores - scores.max(axis=1).reshape(scores.shape[0], 1)
scores = np.exp(scores)
scores = scores / scores.sum(axis=1)

print(scores)

[[0.09003057 0.24472847 0.66524096]]


In [68]:
scores = a
scores = scores - scores.max(axis=1).reshape(scores.shape[0], 1)
scores = np.exp(scores)
sum1 = scores.sum(axis=1).reshape(scores.shape[0], 1)
scores = scores / sum1
print(scores)


[[0.09003057 0.24472847 0.66524096]
 [0.09003057 0.24472847 0.66524096]
 [0.09003057 0.24472847 0.66524096]]


In [ ]:
np.full_like()