In [43]:
import numpy as np
from itertools import product

In [9]:
a = np.array([[0,1,0], [1,0,0],[0,1,0]])

In [3]:
a

array([[0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [14]:
b = np.array([2,3,4]).reshape(3, 1)

In [16]:
c = a * b

In [17]:
c

array([[0, 2, 0],
       [3, 0, 0],
       [0, 4, 0]])

In [23]:
a[(0,1,2), [1,0,1]] = [2,3,4]

In [24]:
a

array([[0, 2, 0],
       [3, 0, 0],
       [0, 4, 0]])

In [29]:
d = np.append(a, [[1],[2],[3]], axis=1).reshape(3, 4)

In [30]:
d

array([[0, 2, 0, 1],
       [3, 0, 0, 2],
       [0, 4, 0, 3]])

In [44]:
list(product([1,2,3], [4,5,6]))

[(1, 4), (1, 5), (1, 6), (2, 4), (2, 5), (2, 6), (3, 4), (3, 5), (3, 6)]